### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by xgp** [MGLL/keycloak-orgs-read-only-attributes-spi#1]
@MGLL Sorry for the roundabout way to contact you, but I realized I don't have your email address. I wanted to let you know (in case you don't already) that there is small Keycloak conference on Thursday in Frankfurt (https://www.keycloak-day.dev/). I will be giving a talk on keycloak-orgs (including a bit about your active org patch), and I have an pass for the streaming if you have interest in watching it. Please email me at `gpatil@phasetwo.io` if you want it.

**Comment by MGLL** [comment]
Hi @xgp I will be surely interested!
Thank you for thinking of me.

I will contact you with the email I'm using for github.
